<?php

namespace Book\ReviewBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatest($limit, $offset)
    {
        $queryBuilder = $this->createQueryBuilder('book');
        $queryBuilder->orderBy('book.timestamp', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit);
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }

    public function getLatestBookQuery()
    {
        $queryBuilder = $this->createQueryBuilder('book');
        $queryBuilder->orderBy('book.timestamp', 'DESC');
        $query = $queryBuilder->getQuery();
        return $query;
    }


    public function getBooksByAuthor()
    {
        $queryBuilder = $this->createQueryBuilder('book');
        $queryBuilder->select('book.bookauthor')->orderBy('book.bookauthor', 'ASC')->distinct();
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }


    public function getBooksForAnAuthor($authorname)
    {
        $queryBuilder = $this->createQueryBuilder('book');
        $queryBuilder->orderBy('book.timestamp', 'DESC')
            ->where('book.bookauthor = :bookauthor')
            ->setParameter('bookauthor',$authorname);
        $query = $queryBuilder->getQuery();
        return $query;
    }


}
