<?php

namespace Book\ReviewBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatest($limit, $offset)
    {
        $queryBuilder = $this->createQueryBuilder('review');
        $queryBuilder->orderBy('review.timestamp', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit);
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }


    public function getQueryForReviews($id)
    {
        $queryBuilder = $this->createQueryBuilder('review');
        $queryBuilder
            ->orderBy('review.timestamp', 'DESC')
            ->where('review.reviewof = :reviewof')
            ->setParameter('reviewof',$id);
        $query = $queryBuilder->getQuery();
        return $query;
    }
}
