
book_index:
    path: /
    defaults: { _controller: BookReviewBundle:Page:index }
    requirements:
        _method: GET

book_about:
    path: /about
    defaults: { _controller: BookReviewBundle:Page:about }
    requirements:
        _method: GET


book_contact:
    path: /contact
    defaults: { _controller: BookReviewBundle:Page:contact }
    requirements:
        _method: GET

viewbook:
    path:     /viewbook/{id}
    defaults: { _controller: BookReviewBundle:BookReview:viewbook }
    requirements:
        _method: POST
        id: \d+
createbook:
    path:     /createbook
    defaults: { _controller: BookReviewBundle:BookReview:createbook }

editbook:
    path:     /editbook/{id}
    defaults: { _controller: BookReviewBundle:BookReview:editbook }
    requirements:
        id: \d+

deletebook:
    path:     /deletebook/{id}
    defaults: { _controller: BookReviewBundle:BookReview:deletebook }
    requirements:
        id: \d+


find_by_author:
    path:     /findbyauthor
    defaults: { _controller: BookReviewBundle:BookReview:findbyauthor }


books_by_author:
    path:     /booksbyauthor/{name}
    defaults: { _controller: BookReviewBundle:BookReview:booksbyauthor }


createreview:
    path:     /createreview/{id}
    defaults: { _controller: BookReviewBundle:Review:createreview }
    requirements:
        id: \d+
editreview:
    path:     /editreview/{id}
    defaults: { _controller: BookReviewBundle:Review:editreview }
    requirements:
        id: \d+
deletereview:
    path:     /deletereview/{id}
    defaults: { _controller: BookReviewBundle:Review:deletereview }
    requirements:
        id: \d+


#GOOGLE BOOK STUFF
books:
    path:     /books
    defaults: { _controller: BookReviewBundle:GoogleApi:books }

book:
    path:     /book/{bookId}
    defaults: { _controller: BookReviewBundle:GoogleApi:book }


books_pagination:
    path:     /books/{page}
    defaults: { _controller: BookReviewBundle:GoogleApi:bookPagination }


adding_google_book:
    path:     /adding/book/{id}
    defaults: { _controller: BookReviewBundle:GoogleApi:addingBook }

one_comic_book:
    path:     /oneComicBook/{id}
    defaults: { _controller: BookReviewBundle:ComicApi:oneComicBook }

comic_books:
    path:     /comicBooks
    defaults: { _controller: BookReviewBundle:ComicApi:comicBooks }


comic_books_pagination:
    path:     /comicbooks/{page}
    defaults: { _controller: BookReviewBundle:ComicApi:comicBookPagination }
