# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_STAFF:       ROLE_STAFF
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern: ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                use_referer: true

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true # can be omitted as its default value

        main:
            anonymous: ~
            # activate different ways to authenticate


            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            logout: ~

            #guard:
            #    authenticators:
            #        - app.security.login_form_authenticator

            form_login:
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: '%secret%'

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/easyadmin, role: ROLE_ADMIN }
       # - { path: ^/editbook, role: ROLE_USER }
       # - { path: ^/createbook, role: ROLE_USER }
       # - { path: ^/deletebook, role: ROLE_USER }
        - { path: ^/editreview, role: ROLE_USER }
        - { path: ^/createreview, role: ROLE_USER }
        - { path: ^/deletereview, role: ROLE_USER }
        - { path: ^/editbook, role: [ROLE_STAFF, ROLE_ADMIN] }
        - { path: ^/createbook, role: [ROLE_STAFF, ROLE_ADMIN] }
        - { path: ^/deletebook, role: [ROLE_STAFF, ROLE_ADMIN] }
        - { path: ^/like, role: ROLE_USER }
        - { path: ^/dislike, role: ROLE_USER }
       # - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
